# This is a basic workflow to help you get started with Actions

name: Deploy to Production

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: Set environmental variable
        run: echo "IMAGE_NAME=$(echo docker.pkg.github.com/${{ github.repository }}/datauno-ui:$(date "+%d%m%y%H%M"))" >> $GITHUB_ENV
      - name: Build the Docker image and publish registry
        run: |
          echo $IMAGE_NAME
          docker build . --file Dockerfile --tag $IMAGE_NAME
          docker login -u sandeep-devarapalli -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
          docker push $IMAGE_NAME
          docker logout docker.pkg.github.com
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        with:
          command: |
            cd /tmp
            ls -a
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.SSH_DEPLOYMENT_KEY }}
          passphrase: ${{ secrets.SSH_DEPLOYMENT_KEY_PASSPHRASE }}
          envs: USERNAME,TOKEN,IMAGE_NAME,REPO
          script: |
            echo "it is working"
            echo $IMAGE_NAME
            whoami
            # Change directory to hackstrap
            echo Changing directory to $HOME/hackstrap
            cd $HOME/hackstrap
            echo current directory $PWD
          
      # - name: Run deploy script on the server
      #   uses: appleboy/ssh-action@master
      #   env:
      #     USERNAME: ${{ secrets.USERNAME }}
      #     TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     REPO: ${{ github.repository }}
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.DEPLOYMENT_KEY }}
      #     envs: USERNAME,TOKEN,IMAGE_NAME,REPO
      #     script: ~/hackstrap/deploy-script.sh $USERNAME $TOKEN $IMAGE_NAME $REPO